# SPDX-FileCopyrightText: 2026 TechFlag
# SPDX-License-Identifier: MIT
"""Repository protocols shared by services and routes."""

from __future__ import annotations

from pathlib import Path
from typing import Protocol

from app.domain.models import (
    ApplicationRecord,
    ApplicationRunRecord,
    ApplicationRunStepRecord,
    ApplicationStepRecord,
    ApplicationVersionRecord,
    DocumentRecord,
    BusinessSkillRecord,
    LlmCallTraceRecord,
    ParseJobRecord,
    PromptConfigRecord,
    PromptRunRecord,
    SchemaTemplateRecord,
    SkillSampleRecord,
    SkillTestRunRecord,
    TaskResultArtifactRecord,
    TaskRecord,
)
from app.schemas.workbench import (
    AdminOverviewResponse,
    ApplicationDetail,
    ApplicationRunDetail,
    ApplicationSummary,
    ApplicationWorkshopStepDraft,
    ApplicationWorkshopStepDraftUpsertRequest,
    CreateCustomerRequest,
    CustomerSummary,
    PromptExecutionContext,
    CustomerWorkspaceResponse,
    DocumentDetail,
    DocumentSummary,
    RegisterDocumentRequest,
    RegisterDocumentResponse,
    PageOperationTargetsResponse,
    WorkbenchDataset,
    TaskSummary,
    UserTaskListResponse,
    WorkbenchTaskDetail,
)


class WorkbenchRepository(Protocol):
    def get_dataset(self, *, include_details: bool = False) -> WorkbenchDataset: ...
    def list_customers(self) -> list[CustomerSummary]: ...
    def create_customer(self, payload: CreateCustomerRequest) -> CustomerSummary: ...
    def get_customer_workspace(self, customerId: str) -> CustomerWorkspaceResponse: ...
    def list_documents(self, customerId: str) -> list[DocumentSummary]: ...
    def get_document(self, customerId: str, documentId: str) -> DocumentDetail: ...
    def register_document(self, customerId: str, payload: RegisterDocumentRequest) -> RegisterDocumentResponse: ...
    def list_customer_tasks(self, customerId: str) -> list[TaskSummary]: ...
    def list_user_tasks(self, userId: str) -> UserTaskListResponse: ...
    def get_admin_overview(self) -> AdminOverviewResponse: ...
    def get_task_summary(self, taskId: str) -> TaskSummary: ...
    def get_task_detail(self, taskId: str, *, lightPromptRuns: bool = False) -> WorkbenchTaskDetail: ...
    def get_task_execution_context(self, taskId: str) -> PromptExecutionContext: ...
    def get_task_page_result_detail(self, taskId: str, runId: str): ...
    def get_task_page_detail(self, taskId: str, pageNo: int): ...
    def get_task_page_operation_targets(self, taskId: str, pageNo: int) -> PageOperationTargetsResponse: ...
    def get_task_record(self, taskId: str) -> TaskRecord: ...
    def get_document_record(self, documentId: str) -> DocumentRecord: ...
    def get_parse_job(self, taskId: str) -> ParseJobRecord: ...
    def list_schema_templates(self) -> list[SchemaTemplateRecord]: ...
    def get_schema_template(self, templateId: str) -> SchemaTemplateRecord: ...
    def save_schema_template(self, template: SchemaTemplateRecord) -> SchemaTemplateRecord: ...
    def list_business_skills(self, customerId: str | None = None) -> list[BusinessSkillRecord]: ...
    def list_business_skills_for_customers(self, customerIds: list[str]) -> list[BusinessSkillRecord]: ...
    def get_business_skill(self, skillId: str, customerId: str | None = None) -> BusinessSkillRecord: ...
    def save_business_skill(self, skill: BusinessSkillRecord) -> BusinessSkillRecord: ...
    def delete_business_skill(self, skillId: str, customerId: str | None = None) -> None: ...
    def move_business_skill(self, skillId: str, sourceCustomerId: str, targetCustomerId: str) -> BusinessSkillRecord: ...
    def list_skill_samples(
        self,
        *,
        kind: str,
        skillId: str,
        customerId: str | None = None,
        limit: int = 20,
    ) -> list[SkillSampleRecord]: ...
    def save_skill_sample(self, sample: SkillSampleRecord) -> SkillSampleRecord: ...
    def list_skill_test_runs(
        self,
        *,
        kind: str,
        skillId: str,
        customerId: str | None = None,
        limit: int = 20,
    ) -> list[SkillTestRunRecord]: ...
    def save_skill_test_run(self, run: SkillTestRunRecord) -> SkillTestRunRecord: ...
    def list_prompt_configs(self, taskId: str) -> list[PromptConfigRecord]: ...
    def save_prompt_config(self, config: PromptConfigRecord) -> PromptConfigRecord: ...
    def list_prompt_runs(
        self,
        taskId: str,
        *,
        runType: str | None = None,
        light: bool = False,
    ) -> list[PromptRunRecord]: ...
    def get_prompt_run(self, runId: str) -> PromptRunRecord: ...
    def save_prompt_run(self, run: PromptRunRecord, *, refresh_task: bool = True) -> PromptRunRecord: ...
    def list_applications(
        self,
        *,
        customerIds: list[str] | None = None,
        publishedOnly: bool = False,
        scope: str | None = None,
    ) -> list[ApplicationSummary]: ...
    def get_application(self, applicationId: str) -> ApplicationRecord: ...
    def save_application(self, application: ApplicationRecord) -> ApplicationRecord: ...
    def list_application_versions(self, applicationId: str) -> list[ApplicationVersionRecord]: ...
    def get_application_version(self, applicationId: str, version: str) -> ApplicationVersionRecord: ...
    def save_application_version(self, version: ApplicationVersionRecord) -> ApplicationVersionRecord: ...
    def list_application_steps(self, applicationId: str, *, versionLabel: str) -> list[ApplicationStepRecord]: ...
    def replace_application_steps(
        self,
        applicationId: str,
        *,
        versionLabel: str,
        steps: list[ApplicationStepRecord],
    ) -> list[ApplicationStepRecord]: ...
    def get_application_detail(
        self,
        applicationId: str,
        *,
        version: str | None = None,
        includeDraft: bool = False,
    ) -> ApplicationDetail: ...
    def save_application_run(self, run: ApplicationRunRecord) -> ApplicationRunRecord: ...
    def get_application_run(self, runId: str) -> ApplicationRunRecord: ...
    def save_application_run_step(self, step: ApplicationRunStepRecord) -> ApplicationRunStepRecord: ...
    def list_application_run_steps(self, runId: str) -> list[ApplicationRunStepRecord]: ...
    def get_application_run_detail(self, runId: str, *, includeFinalOutput: bool = True) -> ApplicationRunDetail: ...
    def list_application_workshop_step_drafts(
        self,
        taskId: str,
        *,
        light: bool = False,
    ) -> list[ApplicationWorkshopStepDraft]: ...
    def get_application_workshop_step_draft(self, taskId: str, draftId: str) -> ApplicationWorkshopStepDraft: ...
    def save_application_workshop_step_draft(
        self,
        taskId: str,
        payload: ApplicationWorkshopStepDraftUpsertRequest,
        *,
        userId: str | None = None,
    ) -> ApplicationWorkshopStepDraft: ...
    def delete_application_workshop_step_draft(self, taskId: str, draftId: str) -> None: ...
    def save_llm_call_trace(self, trace: LlmCallTraceRecord) -> LlmCallTraceRecord: ...
    def list_llm_call_traces(self, taskId: str, *, runId: str | None = None) -> list[LlmCallTraceRecord]: ...
    def save_result_artifact(self, artifact: TaskResultArtifactRecord) -> TaskResultArtifactRecord: ...
    def list_result_artifacts(
        self,
        taskId: str,
        *,
        pageNo: int | None = None,
        runId: str | None = None,
        artifactKind: str | None = None,
        stage: str | None = None,
    ) -> list[TaskResultArtifactRecord]: ...
    def save_page_recognition_snapshots(self, taskId: str, pages: list) -> None: ...
    def replace_operation_targets(self, taskId: str, pageNo: int, sourceRunId: str, targets: list) -> list: ...
    def upsert_parse_job(self, job: ParseJobRecord) -> ParseJobRecord: ...
    def attach_parse_artifacts(self, taskId: str, artifact_urls: dict[str, str | None]) -> None: ...
    def resolve_artifact_absolute_path(self, relativePath: str | None) -> Path | None: ...
